[providers]
  node = {}

[phases.setup]
  nixPkgs = ["...", "unzip", "chromium"]

[variables]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_SKIP_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[phases.build]
  cmds = ["cd web && npm ci", "cd web && npm run build"]

[start]
  cmd = "cd web && npm run start"
